### ISSUE TITLE
It is not recognizing all players

### ISSUE THREAD

**Issue by captchaoss** [Almightygir/fvtt-advanced-loot-sheet-pf1#4]
I have a 5 player game that no matter which type of NPC loot sheet I create (loot or merchant) only 2 of the players are recognized and can interact with the sheet. When I right-click and select Configure Permissions I do have All Players set to None, and all the individual players are listed and set to Observer, but when you open the NPC sheet(s) it is only recognizing the last 2 players. All players can open the loot sheet and see what is in there, but the other 3 players are unable to interact with it. I've tried making multiple NPC sheets in both loot and merchant types, but it is the same every time. And just to rule it out as a potential problem, I am using the PF1:LootSheetPf1NPC sheet type, not the Loot sheet type.

**Comment by Almightygir** [comment]
Hi!

Sorry for the delayed response. Could you please double check for me, in the player list at the bottom left of your foundry screen, if you right click on the players that aren't visible, and in User Configuration, make sure they are assigned a character?

Let me know if it still isn't working. You may need to give me access (as a player) to your game, briefly, so i can debug.

**Comment by captchaoss** [comment]
This resolved the issue.
